### ISSUE TITLE
Couldn't find any versions for "eslint-plugin-jsdoc" that matches "^39.3.2"

### ISSUE THREAD

**Issue by saintdianabless** [IsaacScript/isaacscript#18]
Although version 39.3.2 has been released, it doesn't seem to have been synced to npm.

https://github.com/IsaacScript/isaacscript/blob/46a97bd2fd1b0c042234a89ce6089acb67468a14/packages/isaacscript-lint/package.json#L36
![image](https://user-images.githubusercontent.com/93075932/170301956-5ed11b10-6157-4810-aa13-577eb40f1f9b.png)
![image](https://user-images.githubusercontent.com/93075932/170302921-3a4af25c-9d0f-44cd-9eaf-bba32846e246.png)

**Comment by Zamiell** [comment]
I moved to a monorepo yesterday, so it probably has something to do with that, I'll investigate.

**Comment by josephpercy** [comment]
Honestly it just seems like an issue with the wrong dependency being used. The latest version released of eslint-plugin-jsdoc is 39.3.1 and you reference 39.3.2

Not sure if this would be due to the monorepo at all, but might be an easy fix.

**Comment by Zamiell** [comment]
Also Joseph, you should join the IsaacScript Discord, you can get help faster that way. :)

**Comment by josephpercy** [comment]
It is working now, got past the small dependency issue. Thank you! I will definitely join the discord

**Comment by Zamiell** [comment]
ok, i'll close this then

**Comment by Zamiell** [comment]
More info: It does look like v39.3.2 shows up on NPM now.
https://www.npmjs.com/package/eslint-plugin-jsdoc
