### ISSUE TITLE
Isaac.Spawn #6 Argument (Spawner: Entity)

### ISSUE THREAD

**Issue by dloez** [IsaacScript/isaacscript#28]
Isaac.Spawn 6 argument can be (Entity | Undefined). If you do not define an argument the code is compiled to this following Lua code:

TypeScript:
```typescript
Isaac.Spawn(
  EntityType.PICKUP,
  PickupVariant.COLLECTIBLE,
  FOBO_ID,
  Vector(320, 300),
  Vector(0, 0),
);
```
Lua:
```lua
Isaac.Spawn(
      EntityType.PICKUP,
      PickupVariant.COLLECTIBLE,
      FOBO_ID,
      Vector(320, 300),
      Vector(0, 0)
)
```

The spawner parameter needs to be an Entity or NIL in order to work.

Workarounds:
- Add nil in main.lua (gets deleted each team you modify ts files)
- Add null in Typescript Isaac.Spawn 6 argument (gives "Argument of type 'null' is not assignable to parameter of type 'Entity | undefined'")

**Comment by Zamiell** [comment]
1)

ah, good catch, thanks

see commit https://github.com/IsaacScript/isaacscript/commit/17c59a28e971ccb1b2a7088edf74008c93a1e693

upgrade to v3.0.12 of the defs

2)

> Add null in Typescript Isaac.Spawn 6 argument (gives "Argument of type 'null' is not assignable to parameter of type 'Entity | undefined'")

you should be using undefined for this purpose, not null, see https://isaacscript.github.io/main/javascript-tutorial#nil----undefined

3)

you should not ever be using Isaac.Spawn yourself directly:

```
     * In most cases, you should not be using this method directly, and instead be using the set of
     * `spawn` functions from the standard library. For example:
     *
     * - `spawn` - Will spawn anything with a convenient API.
     * - `spawnWithSeed - Will spawn anything with an API that makes it easy to specify a seed.`
     * - `spawnPickup` - Will spawn a pickup with a convenient API.
     * - `spawnPickupWithSeed - Will spawn a pickup with an API that makes it easy to specify a
     *   seed.`
     * - `spawnKey` - Will spawn a key with a convenient API.
     * - etc.
```

there are spawn functions for every type of entity, and if you need more, i can add them

4) 

join the discord server and I can respond faster to your questions
