### ISSUE TITLE
Does not clone into correct mod folder for Repentance

### ISSUE THREAD

**Issue by Somdudewillson** [IsaacScript/isaacscript#4]
As the title says, isaacscript does not copy into the new mod folder.

**Comment by Zamiell** [comment]
The new mod folder changed, I'm currently updating the program accordingly.

**Comment by Zamiell** [comment]
I normally hang out on Discord.
If you want, you can join the IsaacScript Discord here: https://discord.gg/vu3pFATz

**Comment by Zamiell** [comment]
should be fixed now on v1.0.59
