### ISSUE TITLE
MC_EXECUTE_CMD crashing the game

### ISSUE THREAD

**Issue by laceous** [IsaacScript/isaacscript#45]
Create a simple mod like this:
```
local mod = RegisterMod('zTest', 1)

function mod:onExecuteCmd(cmd, parameters)
  if cmd == 'zTest' then
    return 'Ran zTest'
  end
end

mod:AddCallback(ModCallbacks.MC_EXECUTE_CMD, mod.onExecuteCmd)
```

On its own, this works. As soon as I enable a mod that uses IsaacScript, the game crashes when running the command. I tested with SpiderMod+ and The Babies Mod.

The log just lists:
```
[INFO] - Lua stack trace:
[INFO] - Caught exception, writing minidump...
```

I'm on the latest version of Repentance (1.7.9b)

**Comment by Zamiell** [comment]
this has nothing to do with isaacscript, read the docs https://wofsauge.github.io/IsaacDocs/rep/enums/ModCallbacks.html?h=modcall#mc_execute_cmd

**Comment by Zamiell** [comment]
(in fact, if you had actually used isaacscript for your mod, it would have *prevented* the game from crashing in the first place, showcasing the power of type-safety)

**Comment by laceous** [comment]
```
Returning any value beside nil will cause the game to crash, including a string.
```
That comments seems to be out-of-date considering I can use:

```
>zTest
Ran zTest
```

I can install any number of other Lua mods and  this still works. It's only when installing an IsaacScript mod that the game crashes. Why?

**Comment by Zamiell** [comment]
i dont know, try commenting out stuff line by line until you find the line that causes the crash

**Comment by Zamiell** [comment]
for the record, there's no need to return a string to print something to the console, and the docs don't recommend that you do so anyway
