### ISSUE TITLE
Full Repentance support

### ISSUE THREAD

**Issue by TheChilliPL** [IsaacScript/isaacscript#5]
Is there already full support for Repentance? If not, is there any way to use functions added in Repentance?

(Also, I'd suggest enabling Discussions in repository settings, where IsaacScript users could ask about things that don't really fit as issues.)

**Comment by UrSok** [comment]
There is a discord server:
https://discord.gg/vu3pFATz

**Comment by Zamiell** [comment]
yes, everything should work in rep

**Comment by ShayBox** [comment]
Invite is invalid

**Comment by Zamiell** [comment]
sorry, try with this one
https://discord.gg/KapmKQ2gUD
