### ISSUE TITLE
Predefined linters and formatters

### ISSUE THREAD

**Issue by lajbel** [IsaacScript/isaacscript#51]
It's really necessary for this framework to automatically import personal-styles such `prettierrc.cjs`, `eslintrc.json`, `settings.json` for vscode users, etc? It's kind of annoying delete that stuff, it can't be an option like `isaacscript init --no-formatter --no-linter`

**Comment by Zamiell** [comment]
.prettierrc.cjs just contains prettier defaults and other best-practices, you should never delete it.
.eslintrc.json contains a [suite of rules that are best-practice for the typescript ecosystem](https://typescript-eslint.io/getting-started/), you should not delete it.

if you don't want to use prettier, [you should reconsider](https://github.com/IsaacScript/isaacscript/tree/main/packages/isaacscript-lint#why-code-formatting-is-important).

as for eslint, it is just a no-brainer, it will prevent bugs in your mod for the exact same reason that using typescript will prevent bugs in your mod.

**Comment by Zamiell** [comment]
i will add options if other people in the isaacscript ecosystem want that, but so far you are the only person to ask.
for now, i recommend using prettier/eslint like everyone else does.
