### ISSUE TITLE
There's no way to extend ModCallback enum for custom typed callbacks.

### ISSUE THREAD

**Issue by aleksander-ciesielski** [IsaacScript/isaacscript#52]
Isaac API supports custom callbacks, although in IsaacScript there's no way to extend it as it's tied to `ModCallback` enum, which isn't extensible in TypeScript:

```ts
AddCallback<T extends ModCallback | string>(
  modCallback: T,
  ...args: T extends ModCallback ? AddCallbackParameters[T] : unknown[]
): void;
```
Declaring a new overload for `AddCallback` isn't an option either, as the base signature will always be picked over the new one. A way to fix this issue is to change the guard of `T` to `keyof AddCallbackParameters`, which would allow adding custom callbacks by augmenting `AddCallbackParameters` interface:

```ts
declare "isaac-typescript-definitions" {
  interface AddCallbackParameters {
    MY_CUSTOM_CALLBACK: [(param: boolean) => string];
  }
}
```

**Comment by Zamiell** [comment]
The ModCallback enum is extensible, right?

https://typescripttolua.github.io/play#code/KYOwrgtgBAsg9gEwMIEMA2aBGKDGBrKAbwCgooAFAeQGUAVAfQDlyl6BVcgEQEFaBRKAF4oABgA0pCjQYce-IVACMEgL7FioSLESoM2fEUlkqdejACa9JGzqUY9agAkAkrQUBOT6vVA

**Comment by aleksander-ciesielski** [comment]
Yeah, but you can't extend imported enum - you can only make it working on compile-time by extending declaration. Changing the guard would allow string-based callbacks to be strongly typed (`AddCallback` already accepts strings as events but with `unknown[]` as arguments).
