### ISSUE TITLE
npx isaacscript monitor keeps crashing

### ISSUE THREAD

**Issue by pighel** [IsaacScript/isaacscript#55]
maybe i do not understand something but when i try to execute this command, it fails with
```
Error: npm
Error: ERR! could not determine executable to run
```
but `npx isaacscript init modname` appears to work and mod is created successfully

**Comment by pighel** [comment]
maybe i do not understand something but when i try to execute this command, it fails with
Error: npm
Error: ERR! could not determine executable to run
but 'npx isaacscript init <modname>' appears to work and mod is created successfully

**Comment by Zamiell** [comment]
you don't have to type monitor, as it is the default command.

did you install it globally or something?

**Comment by pighel** [comment]
> did you install it globally or something?

not sure, looks like

anyways, now I just went with `New Folder` > `Git Bash` > `npx isaacscript init` > `npx isaacscript` and everything worked fine (and VSCode got fixed too). I guess I just totally messed up with directories management.
