### ISSUE TITLE
removeAllSacks uses PickupVariant.TRINKET

### ISSUE THREAD

**Issue by Fjara-h** [IsaacScript/isaacscript#61]
https://github.com/IsaacScript/isaacscript/blob/80eb65f943c9cf1ab55ea4958cefbb4a1ce38954/packages/isaacscript-common/src/functions/pickupsSpecific.ts#L307

Should it be PickupVariant.SACK?

**Comment by Zamiell** [comment]
sorry thats a typo

**Comment by Zamiell** [comment]
do you wanna submit a pr?

**Comment by Fjara-h** [comment]
Thanks for fixing it, didn't see the response until now.
