### ISSUE TITLE
`isaac-typescript-definitions` export ESM files instead of CJS ones

### ISSUE THREAD

**Issue by aleksander-ciesielski** [IsaacScript/isaacscript#63]
`isaac-typescript-definitions` export ESM files despite having `"type": "commonjs"` in the `package.json`. Because of that, JS tools (like `vitest`) cannot properly import this package.

**Comment by Zamiell** [comment]
I tried to convert ITD to ESM, but TSTL is currently bugged, see: https://github.com/TypeScriptToLua/TypeScriptToLua/issues/1515

**Comment by Zamiell** [comment]
For now, I think we will have to keep the library as CJS. I have confirmed that the emitted JavaScript files are CJS. Please try on version 37.3.1 and then close the issue if it works.

**Comment by aleksander-ciesielski** [comment]
works like a charm 🎉 tysm
