### ISSUE TITLE
canRunUnlockAchievements deletes donation and rerolls machines

### ISSUE THREAD

**Issue by Fjara-h** [IsaacScript/isaacscript#65]
The [canRunUnlockAchievements function](https://github.com/IsaacScript/isaacscript/blob/79cdf02/packages/isaacscript-common/src/functions/run.ts#L48) when translated to [lua (visible in my mod folder here)](https://github.com/Fjara-h/isaac-tainted-laz-alt-stats/blob/isaacscript/mod/main.lua) causes normal donation machines and reroll machines to be deleted [according to vrcngtrx on my mod's steamcommunity page](https://steamcommunity.com/sharedfiles/filedetails/?id=3014948450&tscn=1698670925). 

I removed it from my code and tested it compiled without the function and it did not delete the machines. Then I also manually replaced the lua code with [planetarium chance's non-issacscript lua code](https://github.com/Sectimus/isaac-planetarium-chance/blob/main/main.lua#L308) which attempts to do the same thing, and it did not cause the machines to be deleted when used.

**Comment by Fjara-h** [comment]
Yes, working on that now.

**Comment by Fjara-h** [comment]
I did test more and eventually got the planetarium chance's code to break as well. The reason my mod breaks it and planetarium chance's does not must be because of (I think) when/how often I checked that function. I changed my code to use a similar update style and it no longer breaks. It is very likely limited to how I was using it, which really wasn't a great way. The docs for the function should maybe have a warning, but I'm not sure exactly what it would be. I used it in onPostRender twice per event, and with the planetarium chance checks, it runs far less often.

**Comment by Zamiell** [comment]
Yeah, since the check involves spawning an entity, it is quite a dirty check, and ideally you want to run it least often as possible. I will add a warning to the JSDoc for the function for this. Should I close this issue?

**Comment by Zamiell** [comment]
I guess another option is to gate this function behind a mandatory ISC feature, which would handle the caching for you. What do you think about that?

**Comment by Fjara-h** [comment]
Yes, this can be closed. The warning should be enough to mitigate it, and I am just now fixing it in my code, but forcing the issue may be for the best.

**Comment by Zamiell** [comment]
Ok, I will add it as a feature in the next version. (Your current code will break accordingly.)

**Comment by Zamiell** [comment]
The new version of the function is now in isaacscript-common v75.0.0.
