### ISSUE TITLE
Error: Save.dat writer subprocess exited with code: 1

### ISSUE THREAD

**Issue by TylerJaacks** [IsaacScript/isaacscript#7]
> npx isaacscript

Automatically monitoring the following for changes:
1) your TypeScript code:     C:\Repositories\revelations\src\**\*.ts
2) the source mod directory: C:\Repositories\revelations\mod

Error: Save.dat writer subprocess exited with code: 1

**Comment by Zamiell** [comment]
does the save dat exist?
