### ISSUE TITLE
[Enhancement] Repentagon Support?

### ISSUE THREAD

**Issue by GamingInfinite** [IsaacScript/isaacscript#71]
Any plans on adding Repentagon extensions to isaacscript or would I need to make my own fork for that?

**Comment by Syntax-Sculptor** [comment]
It is currently being worked on.

**Comment by GamingInfinite** [comment]
yeah... I just noticed that there were already some of the extensions already implemented.  Shoulda read first ig

**Comment by Zamiell** [comment]
should be pretty close after the last PR

**Comment by Syntax-Sculptor** [comment]
Added in c1fd12d6109e00e0d3ebf8abc7e7f1ddbdc77ef0. You can install the package [here](https://www.npmjs.com/package/isaac-typescript-definitions-repentogon)
